#!/bin/sh --

#
# FindAndSetVersion function
#   Find and update version string in form "Version = #.#.#" 
#   Search is: case-insensitive, space, tabs, or nothing around '=', and one or more # in each placeholder.
#   Replace is: performed in-place inside of file; however, a backup (.bak) of the original file is also made.  
#
# NOTE: sed on Mac doesn't include a case-insensitive option.  To keep the search pattern equivalent for both
#       grep and sed, must use an expanded pattern for text where each letter is expressed in both upper/lower case.
#       ex: Ver should be [vV][eE][rR]  
#
function FindAndSetVersion {
if grep -q -E ${VERSIONPATTERN} ${VERSIONFILE} ; then
    if sed -i.bak -E "s/${VERSIONPATTERN}/${VERSIONSTRING}/" ${VERSIONFILE} ; then
        echo "Updated file \"${VERSIONFILE}\" to include \"${VERSIONSTRING}\""
    fi
else
    echo "ERROR: Unable to find version string in file \"${VERSIONFILE}\""
fi
}

VERSION=0.5.6

#
# Adjust BlocklyPropClient.py file
#
VERSIONFILE =BlocklyPropClient.py
VERSIONPATTERN =[vV][eE][rR][sS][iI][oO][nN][[:blank:]]*=[[:blank:]]*\"[0-9]+\.[0-9]+\.[0-9]+\"
VERSIONSTRING ="VERSION = \"${VERSION}\""

FindAndSetVersion


#
# Adjust about.txt file
#
VERSIONFILE =about.txt
VERSIONPATTERN =[vV][eE][rR][sS][iI][oO][nN]:[[:blank:]]*v[[:blank:]]*[0-9]+\.[0-9]+\.[0-9]+
VERSIONSTRING ="Version: v${VERSION}"

FindAndSetVersion


#
# Adjust package/blocklypropclient-installer.iss file
#
VERSIONFILE =package/blocklypropclient-installer.iss
VERSIONPATTERN =[mM][yY][aA][pP][pP][vV][eE][rR][sS][iI][oO][nN][[:blank:]]+\"[0-9]+\.[0-9]+\.[0-9]+\"
VERSIONSTRING ="MyAppVersion \"${VERSION}\""

FindAndSetVersion
